coolsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from f1driver.views import pageNotFound
from coolsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('f1driver.urls'))
]

if settings.DEBUG:
    import  debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

f1driver/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'driver'

urlpatterns = [
    path('', views.DriverHome.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', views.DriverCategory.as_view(), name='category')
]

templates/driver/about.html
{% extends "driver/base.html" %}

{% block content %}
    <h1>{{title}}</h1>
    <p>Содержимое страницы сайта</p>
{% endblock content %}

templates/driver/addpage.html
{% extends "driver/base.html" %}

{% block content %}
	<h1>{{title}}</h1>
	<p>Содержимое страницы</p>
	<form action="{% url 'driver:add_page' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="form-error">{{form.non_field_errors}}</div>

		{% for f in form %}
			<p><label class="form-lable" for="{{f.id_for_label}}">{{f.label}}: </label>{{f}}</p>
			<div class="form-error">{{f.errors}}</div>
		{% endfor %}

		<button type="submit">Добавить</button>
	</form>
{% endblock content %}

templates/driver/base.html
{% load static %}
{% load driver_tags %}
{% load cache %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'driver/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'driver/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'driver:home' %}"><div class="logo"></div></a></li>
			{# {% show_menu %} #}

			{% for m in menu %}
				<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
			{% endfor %}

			{% if request.user.is_authenticated %}
				<li class="last">{{user.username}} | <a href="{% url 'driver:logout' %}">Выйти</a></li>
			{% else %}
				<li class="last"><a href="{% url 'driver:register' %}">Регистрация</a> | <a href="{% url 'driver:login' %}">Войти</a></li>
			{% endif %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		{% if cat_selected == 0 %}
			<li class="selected">Все категории</li>
		{% else %}
			<li><a href="{% url 'driver:home' %}">Все категории</a></li>
		{% endif %}
		{# {% show_categories sort='name' cat_selected=cat_selected %} #}

		{% for cat in cats %}
			{% if cat.get_posts__count > 0 %}
				{% if cat.slug == cat_selected %}
					<li class="selected">{{cat.name}}</li>
				{% else %}
					<li><a href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>	
				{% endif %}
			{% endif %}
		{% endfor %}

		<li class="share">
		<p>Наш канал</p>
		<a class="share-yt" href="https://www.youtube.com" target="_blank" rel="nofollow"></a>
		</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}

{% if page_obj.has_other_pages %}
<nav class="list-pages">
	<ul>
		{% if page_obj.has_previous %}
			<li class="page-num"><a href="?page={{page_obj.previous_page_number}}">&lt;</a></li>
		{% endif %}
		{% for p in paginator.page_range %}
			{% if page_obj.number == p %}
				<li class="page-num page-num-selected">{{p}}</li>
			{% elif p >= page_obj.number|add:-2  and p <= page_obj.number|add:2 %}
				<li class="page-num"><a href="?page={{p}}">{{p}}</a></li>
			{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
			<li class="page-num"><a href="?page={{page_obj.next_page_number}}">&gt;</a></li>
		{% endif %}	
	</ul>
</nav>
{% endif %}

	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2021 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</td></tr></table>
<!-- Конец footer'а и страницы -->
</body>
</html>

templates/driver/contact.html
{% extends "driver/base.html" %}

{% block content %}
	<h1>{{title}}</h1>

	<form action="" method="post">
		{% csrf_token %}
		<div class="form-error">{{form.non_field_errors}}</div>
		{% for f in form %}
			<p><label for="" class="form-label" for="{{f.id_for_label}}">{{f.label}}: </label>{{f}}</p>
			<div class="form-error">{{f.errors}}</div>
		{% endfor %}
		<button type="submit">Отправить</button>
	</form>
{% endblock content %}

templates/driver/index.html
{% extends "driver/base.html" %}

{% block content %}
	<ul class="list-articles">
		{% for post in posts %}
			<li>
				<div class="article-panel">
					<p class="first">Категория: {{post.cat.name}}</p>
					<p class="last">Дата: {{post.time_update|date:"d-m-Y H:i:s"}}</p>
				</div>
				{% if post.photo %}
					<p><img class="img-article-left thumb" src="{{post.photo.url}}" alt=""></p>
				{% endif %}
				<h2>
					{{post.title}}
				</h2>
				{% autoescape on %}
					{{post.content|linebreaks|truncatewords:50}}
				{% endautoescape %}
				<div class="clear"></div>
				<div class="link-read-post">
					<p><a href="{{post.get_absolute_url}}">Читать подробнее</a></p>
				</div>
			</li>
		{% endfor %}
	</ul>	
{% endblock content %}

templates/driver/list_categories.html
{% for cat in cats %}
	{% if cat.slug == cat_selected %}
		<li class="selected">{{cat.name}}</li>
	{% else %}
		<li><a href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>	
	{% endif %}
{% endfor %}

templates/driver/list_menu.html
{% for m in menu %}
	{% if not forloop.last %}
			<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
	{% else %}
			<li class="last"><a href="{% url m.url_name %}">{{m.title}}</a></li>
	{% endif %}
{% endfor %}

templates/driver/login.html
{% extends "driver/base.html" %}

{% block content %}
	<h1>{{title}}</h1>

	<form action="" method="post">
		{% csrf_token %}
		{% for f in form %}
			<p><label for="{{f.id_for_label}}" class="form-label">{{f.label}}: </label>{{f}}</p>
			<div class="form-error">{{f.errors}}</div>
		{% endfor %}
		<button type="submit">Войти</button>
	</form>

{% endblock content %}

templates/driver/post.html
{% extends "driver/base.html" %}

{% block content %}
	<h1>{{post.title}}</h1>
	{% if post.photo %}
		<p><img class="img-article-left" src="{{post.photo.url}}" alt=""></p>
	{% endif %}
	<p>{{post.content|linebreaks}}</p>
{% endblock content %}

templates/driver/register.html
{% extends "driver/base.html" %}

{% block content %}
	<h1>{{title}}</h1>

	<form action="" method="post">
		{% csrf_token %}
		{% for f in form %}
			<p><label for="{{f.id_for_label}}" class="form-label">{{f.label}}: </label>{{f}}</p>
			<div class="form-error">{{f.errors}}</div>
		{% endfor %}
		<button type="submit">Регистрация</button>
	</form>
{% endblock content %}